// src/lib/supabase/database.types.ts
// Generated by: npx supabase gen types typescript --local > src/lib/supabase/database.types.ts
// Run this after running migrations locally.
// Placeholder structure — replace with generated output.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          role: 'super_admin' | 'quiz_admin' | 'moderator' | 'participant' | 'display'
          avatar_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      competitions: {
        Row: {
          id: string
          title: string
          description: string | null
          school_year: string | null
          subject: string | null
          created_by: string
          is_active: boolean
          allow_negative_marking: boolean
          negative_mark_value: number
          allow_speed_bonus: boolean
          speed_bonus_max: number
          team_mode: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['competitions']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['competitions']['Insert']>
      }
      sessions: {
        Row: {
          id: string
          competition_id: string
          title: string
          session_code: string
          status: 'draft' | 'lobby' | 'active' | 'paused' | 'completed' | 'archived'
          created_by: string
          current_round_id: string | null
          current_question_index: number
          answer_window_state: 'closed' | 'open' | 'locked'
          reveal_state: 'hidden' | 'distribution_only' | 'answer_revealed' | 'leaderboard_revealed'
          privacy_mode: boolean
          show_fastest_answer: boolean
          show_distribution: boolean
          started_at: string | null
          ended_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['sessions']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['sessions']['Insert']>
      }
      rounds: {
        Row: {
          id: string
          session_id: string
          title: string
          mode: 'fastest_finger' | 'classic_mcq' | 'personal_cbt' | 'sudden_death' | 'practice' | 'buzzer'
          order_index: number
          status: 'pending' | 'active' | 'paused' | 'completed'
          time_limit_seconds: number
          base_points: number
          allow_negative: boolean
          negative_value: number
          allow_speed_bonus: boolean
          speed_bonus_max: number
          eliminate_on_wrong: boolean
          started_at: string | null
          ended_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['rounds']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['rounds']['Insert']>
      }
      questions: {
        Row: {
          id: string
          round_id: string
          question_text: string
          question_type: 'multiple_choice' | 'true_false' | 'short_answer'
          image_url: string | null
          order_index: number
          time_limit_seconds: number | null
          base_points: number | null
          explanation: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['questions']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['questions']['Insert']>
      }
      question_options: {
        Row: {
          id: string
          question_id: string
          option_label: string
          option_text: string
          is_correct: boolean
          order_index: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['question_options']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['question_options']['Insert']>
      }
      teams: {
        Row: {
          id: string
          session_id: string
          team_name: string
          color_hex: string
          total_score: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['teams']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['teams']['Insert']>
      }
      participants: {
        Row: {
          id: string
          session_id: string
          display_name: string
          team_id: string | null
          user_id: string | null
          join_code: string
          is_eliminated: boolean
          is_online: boolean
          total_score: number
          correct_count: number
          wrong_count: number
          avg_response_ms: number | null
          joined_at: string
          last_seen_at: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['participants']['Row'], 'id' | 'joined_at' | 'last_seen_at' | 'created_at'>
        Update: Partial<Database['public']['Tables']['participants']['Insert']>
      }
      answers: {
        Row: {
          id: string
          participant_id: string
          session_id: string
          round_id: string
          question_id: string
          selected_option_id: string | null
          submitted_at_server: string
          response_time_ms: number | null
          is_correct: boolean | null
          awarded_points: number
          submission_status: 'submitted' | 'invalidated' | 'overridden' | 'late'
          fastest_rank: number | null
          override_by: string | null
          override_reason: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['answers']['Row'], 'id' | 'submitted_at_server' | 'created_at'>
        Update: Partial<Database['public']['Tables']['answers']['Insert']>
      }
      display_state: {
        Row: {
          id: string
          session_id: string
          current_question_id: string | null
          current_round_id: string | null
          reveal_state: 'hidden' | 'distribution_only' | 'answer_revealed' | 'leaderboard_revealed'
          answer_window_state: 'closed' | 'open' | 'locked'
          timer_started_at: string | null
          timer_duration_seconds: number | null
          timer_paused_at: string | null
          show_leaderboard: boolean
          show_distribution: boolean
          show_fastest: boolean
          fastest_participant_id: string | null
          fastest_response_ms: number | null
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['display_state']['Row'], 'id' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['display_state']['Insert']>
      }
      leaderboard_snapshots: {
        Row: {
          id: string
          session_id: string
          question_id: string | null
          round_id: string | null
          snapshot_data: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['leaderboard_snapshots']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['leaderboard_snapshots']['Insert']>
      }
      audit_logs: {
        Row: {
          id: string
          session_id: string | null
          performed_by: string | null
          action: string
          entity_type: string | null
          entity_id: string | null
          before_data: Json | null
          after_data: Json | null
          ip_address: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'created_at'>
        Update: never
      }
    }
    Views: Record<string, never>
    Functions: {
      get_user_role: {
        Args: Record<string, never>
        Returns: string
      }
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
    }
    Enums: {
      app_role: 'super_admin' | 'quiz_admin' | 'moderator' | 'participant' | 'display'
      round_mode: 'fastest_finger' | 'classic_mcq' | 'personal_cbt' | 'sudden_death' | 'practice' | 'buzzer'
      session_status: 'draft' | 'lobby' | 'active' | 'paused' | 'completed' | 'archived'
      round_status: 'pending' | 'active' | 'paused' | 'completed'
      question_type: 'multiple_choice' | 'true_false' | 'short_answer'
      reveal_state: 'hidden' | 'distribution_only' | 'answer_revealed' | 'leaderboard_revealed'
      submission_status: 'submitted' | 'invalidated' | 'overridden' | 'late'
      answer_window_state: 'closed' | 'open' | 'locked'
    }
  }
}
